version: '3.8'
services:
  db:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - vote-net

  redis:
    image: redis:7
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - vote-net

  app:
    build: .
    ports:
      - '3000:3000'
    # 환경변수는 .env 파일에서 일괄 관리합니다
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      chat-server:
        condition: service_started
      notification-server:
        condition: service_started
    restart: always
    networks:
      - vote-net

  chat-server:
    build:
      context: ./server/chat-server
      dockerfile: Dockerfile
    ports:
      - '5001:5001'
    # 환경변수는 .env 파일에서 일괄 관리합니다
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    restart: always
    networks:
      - vote-net

  notification-server:
    build:
      context: ./server/notification-server
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    # 환경변수는 .env 파일에서 일괄 관리합니다
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    restart: always
    networks:
      - vote-net

volumes:
  db_data:
  uploads_data:

networks:
  vote-net:
    driver: bridge
