version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - vote-net

  app:
    env_file:
      - .env
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/mydb
      NEXT_PUBLIC_SOCKET_URL: http://socket-server:4000
    depends_on:
      - db
    volumes:
      - uploads_data:/app/uploads
    networks:
      - vote-net

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    env_file:
      - .env.local
    environment:
      - NEXT_PUBLIC_SOCKET_URL=http://socket-server:4000
    depends_on:
      - socket-server
    networks:
      - vote-net

  socket-server:
    build:
      context: .
      dockerfile: Dockerfile.socket
    command: node server/socket-server.js
    ports:
      - '4000:4000'
    restart: always
    environment:
      - NEXT_PUBLIC_REDIS_URL=redis://redis:6379
      - NEXT_PUBLIC_CHAT_SERVER_PORT=5001
    networks:
      - vote-net

  redis:
    image: redis:7
    container_name: vote-app-redis
    ports:
      - '6379:6379'
    restart: always
    networks:
      - vote-net

volumes:
  db_data:
  uploads_data:

networks:
  vote-net:
    driver: bridge
